### ISSUE TITLE
Error when select Webcam 

### ISSUE THREAD

**Issue by brian-sj** [mesta1/Recording-video-with-c-#3] opened 2018-02-28 02:14 UTC
Thank your example.

I have problem with this source. 
Desktop and IPcammera works good.

But when i select webcam,  It make's error.

_```
_   An unhandled exception of type 'System.ArgumentException' occurred in WindowsBase.dll.
     Must create DependencySource on same Thread as the DependencyObject_
```_ 

This error occur irregularly  in about 10 seconds . 
Pls help.

**Comment by mesta1** [comment] 2018-03-01 22:01
This should be fixed now. Strange that I couldn't reproduce it before with my previous camera.

**Closed as completed** 2018-03-01 22:02 UTC
Labels: bug
